package com.doubledimple.ociserver.third.netdata;

import cn.hutool.core.lang.UUID;
import com.doubledimple.ocicommon.param.ScriptResult;
import com.doubledimple.ocicommon.utils.JschUtils;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Component;

import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.InetAddress;
import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * NetData管理工具类
 * 支持本地Master安装和远程Child节点配置
 */
@Component
@Slf4j
public class NetDataManager {

    private static final String NETDATA_INSTALL_SCRIPT_MAC = "brew install netdata";
    private static final String NETDATA_INSTALL_SCRIPT_LINUX = "bash <(curl -Ss https://my-netdata.io/kickstart.sh)";
    private static final String STREAM_CONF_PATH = "/etc/netdata/stream.conf";
    private static final String STREAM_CONF_PATH_MAC = "/usr/local/etc/netdata/stream.conf";
    private static final int NETDATA_PORT = 19999;

    private String masterApiKey;

    /**
     * 检查操作系统类型
     */
    private boolean isMacOS() {
        return System.getProperty("os.name").toLowerCase().contains("mac");
    }

    /**
     * 获取配置文件路径
     */
    private String getStreamConfPath() {
        return isMacOS() ? STREAM_CONF_PATH_MAC : STREAM_CONF_PATH;
    }
    public boolean isNetDataInstalled() {
        try {
            ProcessBuilder pb = new ProcessBuilder("which", "netdata");
            Process process = pb.start();
            return process.waitFor() == 0;
        } catch (Exception e) {
            log.error("检查NetData安装状态失败", e);
            return false;
        }
    }

    /**
     * 在当前机器安装NetData作为Master节点
     */
    public boolean installMasterOnCurrentMachine() {
        try {
            log.info("开始检查并安装NetData Master节点...");

            // 先检查是否已安装
            if (isNetDataInstalled()) {
                log.info("NetData已安装，跳过安装步骤");
            } else {
                log.info("NetData未安装，开始安装...");
                // 执行安装脚本
                if (!executeInstallScript()) {
                    return false;
                }
                log.info("NetData安装完成");
            }

            // 配置为Master节点
            log.info("配置Master节点...");
            if (!configureMasterNode()) {
                return false;
            }

            // 启动并启用服务
            log.info("启动NetData服务...");
            if (!enableNetDataService()) {
                return false;
            }

            log.info("NetData Master节点安装配置完成！");
            log.info("访问地址: http://{}:{}", getMasterAddress(), NETDATA_PORT);
            return true;

        } catch (Exception e) {
            log.error("安装NetData Master失败", e);
            return false;
        }
    }

    /**
     * 执行NetData安装脚本
     */
    private boolean executeInstallScript() throws IOException, InterruptedException {
        ProcessBuilder pb;

        if (isMacOS()) {
            // Mac使用Homebrew安装
            log.info("Mac环境，使用Homebrew安装NetData...");
            pb = new ProcessBuilder("brew", "install", "netdata");
        } else {
            // Linux使用官方脚本
            pb = new ProcessBuilder("bash", "-c", NETDATA_INSTALL_SCRIPT_LINUX);
        }

        pb.redirectErrorStream(true);
        Process process = pb.start();

        // 实时输出安装日志
        try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
            String line;
            while ((line = reader.readLine()) != null) {
                log.info("安装日志: {}", line);
            }
        }

        boolean success = process.waitFor(300, TimeUnit.SECONDS) && process.exitValue() == 0;
        if (!success) {
            log.error("NetData安装脚本执行失败，退出码: {}", process.exitValue());
        }
        return success;
    }

    /**
     * 配置当前机器为Master节点
     */
    private boolean configureMasterNode() {
        try {
            // 生成API Key
            this.masterApiKey = UUID.randomUUID().toString();

            String streamConfig = String.format(
                    "# NetData Master Configuration\n" +
                            "# Generated by NetDataManager\n\n" +
                            "[%s]\n" +
                            "    enabled = yes\n" +
                            "    allow from = *\n" +
                            "    default history = 3600\n" +
                            "    default memory = ram\n" +
                            "    health enabled by default = auto\n" +
                            "    default postpone alarms on connect seconds = 60\n",
                    masterApiKey);

            // 写入配置文件
            String confPath = getStreamConfPath();
            try (FileWriter writer = new FileWriter(confPath)) {
                writer.write(streamConfig);
            }

            log.info("Master节点配置完成，API Key: {}", masterApiKey);
            return true;

        } catch (Exception e) {
            log.error("配置Master节点失败", e);
            return false;
        }
    }

    /**
     * 启用NetData服务
     */
    private boolean enableNetDataService() throws IOException, InterruptedException {
        if (isMacOS()) {
            // Mac使用brew services管理
            ProcessBuilder startPb = new ProcessBuilder("brew", "services", "start", "netdata");
            Process startProcess = startPb.start();
            if (startProcess.waitFor() != 0) {
                log.error("启动NetData服务失败");
                return false;
            }
            log.info("NetData服务已通过brew services启动");
        } else {
            // Linux使用systemctl
            ProcessBuilder restartPb = new ProcessBuilder("sudo", "systemctl", "restart", "netdata");
            Process restartProcess = restartPb.start();
            if (restartProcess.waitFor() != 0) {
                log.error("重启NetData服务失败");
                return false;
            }

            ProcessBuilder enablePb = new ProcessBuilder("sudo", "systemctl", "enable", "netdata");
            Process enableProcess = enablePb.start();
            if (enableProcess.waitFor() != 0) {
                log.error("设置NetData开机自启失败");
                return false;
            }
        }

        // 检查服务状态
        return checkNetDataStatus();
    }

    /**
     * 检查NetData服务状态
     */
    public boolean checkNetDataStatus() {
        try {
            ProcessBuilder pb;
            if (isMacOS()) {
                pb = new ProcessBuilder("brew", "services", "list");
            } else {
                pb = new ProcessBuilder("systemctl", "is-active", "netdata");
            }

            Process process = pb.start();

            try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
                String line;
                boolean isActive = false;

                if (isMacOS()) {
                    // 检查brew services输出中是否有netdata started
                    while ((line = reader.readLine()) != null) {
                        if (line.contains("netdata") && line.contains("started")) {
                            isActive = true;
                            break;
                        }
                    }
                } else {
                    // Linux检查systemctl输出
                    line = reader.readLine();
                    isActive = "active".equals(line);
                }

                log.info("NetData服务状态: {}", isActive ? "运行中" : "未运行");
                return isActive;
            }
        } catch (Exception e) {
            log.error("检查NetData服务状态失败", e);
            return false;
        }
    }

    /**
     * 在远程服务器上安装NetData作为Master节点
     *
     * @param host 远程服务器地址
     * @param username SSH用户名
     * @param password SSH密码
     * @param port SSH端口
     * @return 是否安装成功
     */
    private boolean installMasterOnRemoteServer(String host, String username, String password, int port) {
        try {
            log.info("开始在远程服务器 {}:{} 安装NetData Master节点...", host, port);

            // 生成Master安装脚本
            String masterInstallScript = generateMasterInstallScript(host);
            log.info("生成Master节点安装脚本完成");

            // 通过SSH执行脚本
            log.info("通过SSH连接到 {}:{} 执行Master安装脚本...", host, port);
            ScriptResult result = JschUtils.executeScriptJsch(host, username, password, port, masterInstallScript);

            // 检查执行结果
            if (result.isSuccess() && result.getOutput() != null && result.getOutput().contains("Master节点安装配置成功")) {
                log.info("远程服务器 {} Master节点安装配置成功", host);
                log.info("Master地址: http://{}:{}", host, NETDATA_PORT);
                log.info("执行输出: {}", result.getOutput());

                // 保存远程Master信息
                this.masterApiKey = extractApiKeyFromResult(result.getOutput());
                this.remoteMasterHost = host; // 设置远程Master地址

                return true;
            } else {
                log.error("远程服务器 {} Master节点安装配置失败", host);
                log.error("退出码: {}", result.getExitCode());
                log.error("标准输出: {}", result.getOutput());
                log.error("错误输出: {}", result.getError());
                return false;
            }

        } catch (Exception e) {
            log.error("在远程服务器安装Master节点失败，服务器: {}:{}", host, port, e);
            return false;
        }
    }

    /**
     * 生成Master节点安装脚本（用于远程服务器）
     */
    private String generateMasterInstallScript(String masterHost) {
        // 生成API Key
        String apiKey = UUID.randomUUID().toString();
        this.masterApiKey = apiKey;

        return String.format(
                "#!/bin/bash\n\n" +
                        "echo \"开始安装NetData Master节点...\"\n\n" +
                        "# 检查是否已安装NetData\n" +
                        "if command -v netdata >/dev/null 2>&1; then\n" +
                        "    echo \"NetData已安装，跳过安装步骤\"\n" +
                        "else\n" +
                        "    echo \"NetData未安装，开始安装...\"\n" +
                        "    \n" +
                        "    # 检测系统类型并安装\n" +
                        "    if [ -f /etc/debian_version ]; then\n" +
                        "        # Debian/Ubuntu系统\n" +
                        "        echo \"检测到Debian/Ubuntu系统，使用apt安装...\"\n" +
                        "        apt update\n" +
                        "        apt install -y netdata\n" +
                        "    elif [ -f /etc/redhat-release ]; then\n" +
                        "        # CentOS/RHEL系统\n" +
                        "        echo \"检测到CentOS/RHEL系统，使用yum安装...\"\n" +
                        "        yum install -y epel-release\n" +
                        "        yum install -y netdata\n" +
                        "    else\n" +
                        "        # 其他系统，尝试官方脚本\n" +
                        "        echo \"尝试使用官方安装脚本...\"\n" +
                        "        # 使用wget作为备选方案\n" +
                        "        if command -v wget >/dev/null 2>&1; then\n" +
                        "            wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh\n" +
                        "            bash /tmp/netdata-kickstart.sh --non-interactive\n" +
                        "        elif command -v curl >/dev/null 2>&1; then\n" +
                        "            curl -Ss https://my-netdata.io/kickstart.sh > /tmp/netdata-kickstart.sh\n" +
                        "            bash /tmp/netdata-kickstart.sh --non-interactive\n" +
                        "        else\n" +
                        "            echo \"错误：系统缺少wget和curl，无法下载安装脚本\"\n" +
                        "            exit 1\n" +
                        "        fi\n" +
                        "    fi\n" +
                        "    \n" +
                        "    # 检查安装是否成功\n" +
                        "    if command -v netdata >/dev/null 2>&1; then\n" +
                        "        echo \"NetData安装完成\"\n" +
                        "    else\n" +
                        "        echo \"NetData安装失败\"\n" +
                        "        exit 1\n" +
                        "    fi\n" +
                        "fi\n\n" +
                        "# 配置Master节点\n" +
                        "echo \"配置Master节点...\"\n" +
                        "cat > /etc/netdata/stream.conf << 'EOF'\n" +
                        "# NetData Master Configuration\n" +
                        "# Generated by NetDataManager\n\n" +
                        "[%s]\n" +
                        "    enabled = yes\n" +
                        "    allow from = *\n" +
                        "    default history = 3600\n" +
                        "    default memory = ram\n" +
                        "    health enabled by default = auto\n" +
                        "    default postpone alarms on connect seconds = 60\n" +
                        "EOF\n\n" +
                        "# 重启NetData服务\n" +
                        "echo \"重启NetData服务...\"\n" +
                        "systemctl restart netdata\n" +
                        "systemctl enable netdata\n\n" +
                        "# 检查服务状态\n" +
                        "if systemctl is-active --quiet netdata; then\n" +
                        "    echo \"Master节点安装配置成功！\"\n" +
                        "    echo \"访问地址: http://%s:%d\"\n" +
                        "    echo \"API Key: %s\"\n" +
                        "else\n" +
                        "    echo \"NetData服务启动失败\"\n" +
                        "    exit 1\n" +
                        "fi\n",
                apiKey, masterHost, NETDATA_PORT, apiKey);
    }

    /**
     * 从执行结果中提取API Key
     */
    private String extractApiKeyFromResult(String result) {
        if (result != null && result.contains("API Key: ")) {
            try {
                String[] lines = result.split("\n");
                for (String line : lines) {
                    if (line.contains("API Key: ")) {
                        return line.substring(line.indexOf("API Key: ") + 9).trim();
                    }
                }
            } catch (Exception e) {
                log.warn("提取API Key失败，使用默认值", e);
            }
        }
        return this.masterApiKey; // 返回生成时的API Key
    }

    /**
     * 获取Master节点地址（支持本机和远程）
     */
    public String getMasterAddress() {
        try {
            return InetAddress.getLocalHost().getHostAddress();
        } catch (Exception e) {
            log.warn("获取本机IP失败，使用localhost");
            return "localhost";
        }
    }

    /**
     * 设置Master节点地址（用于远程Master）
     */
    private String remoteMasterHost;

    public void setMasterHost(String masterHost) {
        this.remoteMasterHost = masterHost;
    }

    public String getCurrentMasterAddress() {
        return remoteMasterHost != null ? remoteMasterHost : getMasterAddress();
    }

    /**
     * 获取Master节点完整URL
     */
    public String getMasterUrl() {
        return String.format("http://%s:%d", getCurrentMasterAddress(), NETDATA_PORT);
    }

    /**
     * 获取Master API Key
     */
    public String getMasterApiKey() {
        return this.masterApiKey;
    }

    /**
     * 生成Child节点配置脚本
     * 这个脚本可以通过你的SSH工具在远程VPS上执行
     */
    public String generateChildInstallScript(String masterAddress,String masterApiKey) {
        String master = "";
        if (StringUtils.isNotBlank(masterAddress)){
            master = masterAddress;
        }else{
            master = getCurrentMasterAddress();
        }
        return String.format(
                "#!/bin/bash\n\n" +
                        "# 安装NetData\n" +
                        "echo \"开始安装NetData...\"\n" +
                        "\n" +
                        "# 检查是否已安装NetData\n" +
                        "if command -v netdata >/dev/null 2>&1; then\n" +
                        "    echo \"NetData已安装，跳过安装步骤\"\n" +
                        "else\n" +
                        "    echo \"NetData未安装，开始安装...\"\n" +
                        "    \n" +
                        "    # 检测系统类型并安装\n" +
                        "    if [ -f /etc/debian_version ]; then\n" +
                        "        # Debian/Ubuntu系统\n" +
                        "        echo \"检测到Debian/Ubuntu系统，使用apt安装...\"\n" +
                        "        apt update\n" +
                        "        apt install -y netdata\n" +
                        "    elif [ -f /etc/redhat-release ]; then\n" +
                        "        # CentOS/RHEL系统\n" +
                        "        echo \"检测到CentOS/RHEL系统，使用yum安装...\"\n" +
                        "        yum install -y epel-release\n" +
                        "        yum install -y netdata\n" +
                        "    else\n" +
                        "        # 其他系统，尝试官方脚本\n" +
                        "        echo \"尝试使用官方安装脚本...\"\n" +
                        "        # 使用wget作为备选方案\n" +
                        "        if command -v wget >/dev/null 2>&1; then\n" +
                        "            wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh\n" +
                        "            bash /tmp/netdata-kickstart.sh --non-interactive\n" +
                        "        elif command -v curl >/dev/null 2>&1; then\n" +
                        "            curl -Ss https://my-netdata.io/kickstart.sh > /tmp/netdata-kickstart.sh\n" +
                        "            bash /tmp/netdata-kickstart.sh --non-interactive\n" +
                        "        else\n" +
                        "            echo \"错误：系统缺少wget和curl，无法下载安装脚本\"\n" +
                        "            exit 1\n" +
                        "        fi\n" +
                        "    fi\n" +
                        "    \n" +
                        "    # 检查安装是否成功\n" +
                        "    if command -v netdata >/dev/null 2>&1; then\n" +
                        "        echo \"NetData安装完成\"\n" +
                        "    else\n" +
                        "        echo \"NetData安装失败\"\n" +
                        "        exit 1\n" +
                        "    fi\n" +
                        "fi\n\n" +
                        "# 配置为Child节点\n" +
                        "echo \"配置Child节点...\"\n" +
                        "cat > /etc/netdata/stream.conf << 'EOF'\n" +
                        "[stream]\n" +
                        "    enabled = yes\n" +
                        "    destination = %s:%d\n" +
                        "    api key = %s\n" +
                        "    timeout seconds = 60\n" +
                        "    default port = 19999\n" +
                        "    send charts matching = *\n" +
                        "    buffer size bytes = 1048576\n" +
                        "    reconnect delay seconds = 5\n" +
                        "    initial clock resync iterations = 60\n" +
                        "EOF\n\n" +
                        "# 重启服务\n" +
                        "echo \"重启NetData服务...\"\n" +
                        "systemctl restart netdata\n" +
                        "systemctl enable netdata\n\n" +
                        "# 检查状态\n" +
                        "if systemctl is-active --quiet netdata; then\n" +
                        "    echo \"Child节点配置成功！\"\n" +
                        "    echo \"数据将推送到: %s:%d\"\n" +
                        "else\n" +
                        "    echo \"Child节点配置失败，请检查日志\"\n" +
                        "    exit 1\n" +
                        "fi\n",
                master, NETDATA_PORT, masterApiKey, master, NETDATA_PORT);
    }

    /**
     * 生成Child节点配置命令（不包含安装，仅配置）
     * 适用于已安装NetData的VPS
     */
    public String generateChildConfigScript() {
        return String.format(
                "# 配置现有NetData为Child节点\n" +
                        "cat > /etc/netdata/stream.conf << 'EOF'\n" +
                        "[stream]\n" +
                        "    enabled = yes\n" +
                        "    destination = %s:%d\n" +
                        "    api key = %s\n" +
                        "    timeout seconds = 60\n" +
                        "    default port = 19999\n" +
                        "    send charts matching = *\n" +
                        "    buffer size bytes = 1048576\n" +
                        "    reconnect delay seconds = 5\n" +
                        "    initial clock resync iterations = 60\n" +
                        "EOF\n\n" +
                        "# 重启服务\n" +
                        "systemctl restart netdata\n\n" +
                        "echo \"Child节点配置完成，数据推送到: %s:%d\"\n",
                getCurrentMasterAddress(), NETDATA_PORT, masterApiKey, getCurrentMasterAddress(), NETDATA_PORT);
    }

    /**
     * 验证Master节点是否正常工作
     */
    public boolean validateMasterNode() {
        try {
            // 检查端口是否开放
            ProcessBuilder pb = new ProcessBuilder("netstat", "-tlnp");
            Process process = pb.start();

            try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    if (line.contains(":" + NETDATA_PORT)) {
                        log.info("NetData端口{}已开放", NETDATA_PORT);
                        return true;
                    }
                }
            }

            log.warn("NetData端口{}未开放", NETDATA_PORT);
            return false;

        } catch (Exception e) {
            log.error("验证Master节点失败", e);
            return false;
        }
    }

    /**
     * 获取NetData API信息
     */
    public String getNetDataApiInfo() {
        try {
            ProcessBuilder pb = new ProcessBuilder("curl", "-s",
                    getMasterUrl() + "/api/v1/info");
            Process process = pb.start();

            try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()))) {
                StringBuilder response = new StringBuilder();
                String line;
                while ((line = reader.readLine()) != null) {
                    response.append(line);
                }
                return response.toString();
            }
        } catch (Exception e) {
            log.error("获取NetData API信息失败", e);
            return null;
        }
    }

    /**
     * 一键在远程VPS上安装并配置Child节点
     *
     * @param host VPS主机地址
     * @param username SSH用户名
     * @param password SSH密码
     * @param port SSH端口
     * @return 安装配置是否成功
     */
    public boolean installChildNodeOnVPS(String masterAddress,String masterApiKey,String host, String username, String password, int port) {
        try {
            log.info("开始在VPS {}:{} 安装NetData Child节点...", host, port);

            // 检查Master节点状态
            if (masterApiKey == null || masterApiKey.isEmpty()) {
                log.error("Master节点未初始化或API Key为空，请先安装Master节点");
                return false;
            }

            // 生成安装和配置脚本
            String installScript = generateChildInstallScript(masterAddress,masterApiKey);
            log.info("生成Child节点安装脚本完成");

            // 通过SSH执行脚本
            log.info("通过SSH连接到 {}:{} 执行安装脚本...", host, port);
            ScriptResult result = JschUtils.executeScriptJsch(host, username, password, port, installScript);

            // 检查执行结果
            if (result.isSuccess() && result.getOutput() != null && result.getOutput().contains("Child节点配置成功")) {
                log.info("VPS {} Child节点安装配置成功", host);
                log.info("执行输出: {}", result.getOutput());
                return true;
            } else {
                log.error("VPS {} Child节点安装配置失败", host);
                log.error("退出码: {}", result.getExitCode());
                log.error("标准输出: {}", result.getOutput());
                log.error("错误输出: {}", result.getError());
                return false;
            }

        } catch (Exception e) {
            log.error("安装Child节点失败，VPS: {}:{}", host, port, e);
            return false;
        }
    }

    /**
     * 批量安装Child节点
     *
     * @param vpsInfos VPS信息列表
     * @return 成功安装的数量
     */
    public int batchInstallChildNodes(String masterAddress,String masterApiKey,List<VpsInfo> vpsInfos) {
        int successCount = 0;

        log.info("开始批量安装 {} 个Child节点...", vpsInfos.size());

        for (VpsInfo vps : vpsInfos) {
            try {
                log.info("正在处理VPS: {}", vps.getHost());

                boolean success = installChildNodeOnVPS(masterAddress,masterApiKey,
                        vps.getHost(),
                        vps.getUsername(),
                        vps.getPassword(),
                        vps.getPort()
                );

                if (success) {
                    successCount++;
                    log.info("VPS {} 安装成功 ({}/{})", vps.getHost(), successCount, vpsInfos.size());
                } else {
                    log.warn("VPS {} 安装失败", vps.getHost());
                }

                // 避免并发过多，稍作延迟
                Thread.sleep(2000);

            } catch (Exception e) {
                log.error("处理VPS {}失败", vps.getHost(), e);
            }
        }

        log.info("批量安装完成，成功: {}, 失败: {}", successCount, vpsInfos.size() - successCount);
        return successCount;
    }

    /**
     * 仅配置已安装NetData的VPS为Child节点
     * 适用于已安装NetData但未配置为Child的VPS
     */
    public boolean configureExistingNetDataAsChild(String host, String username, String password, int port) {
        try {
            log.info("配置已安装的NetData为Child节点: {}:{}", host, port);

            if (masterApiKey == null || masterApiKey.isEmpty()) {
                log.error("Master节点未初始化，请先安装Master节点");
                return false;
            }

            // 生成配置脚本（不包含安装）
            String configScript = generateChildConfigScript();

            // 执行配置脚本
            ScriptResult result = JschUtils.executeScriptJsch(host, username, password, port, configScript);

            if (result.isSuccess() && result.getOutput() != null && result.getOutput().contains("Child节点配置完成")) {
                log.info("VPS {} Child节点配置成功", host);
                log.info("执行输出: {}", result.getOutput());
                return true;
            } else {
                log.error("VPS {} Child节点配置失败", host);
                log.error("退出码: {}", result.getExitCode());
                log.error("标准输出: {}", result.getOutput());
                log.error("错误输出: {}", result.getError());
                return false;
            }

        } catch (Exception e) {
            log.error("配置Child节点失败: {}:{}", host, port, e);
            return false;
        }
    }

    /**
     * 安装Master节点 - 本机安装
     * 一键完成在当前机器上检查、安装、配置Master节点的所有操作
     *
     * @return 是否安装成功
     */
    public boolean installMaster() {
        return installMasterOnCurrentMachine();
    }

    /**
     * 安装Master节点 - 远程安装
     * 一键完成在指定服务器上安装和配置Master节点的所有操作
     *
     * @param host 服务器主机地址
     * @param username SSH用户名
     * @param password SSH密码
     * @param port SSH端口
     * @return 是否安装成功
     */
    public boolean installMaster(String host, String username, String password, int port) {
        return installMasterOnRemoteServer(host, username, password, port);
    }

    /**
     * VPS信息类
     */
    public static class VpsInfo {
        private String host;
        private String username;
        private String password;
        private int port;

        public VpsInfo(String host, String username, String password, int port) {
            this.host = host;
            this.username = username;
            this.password = password;
            this.port = port;
        }

        // Getters and setters
        public String getHost() { return host; }
        public void setHost(String host) { this.host = host; }

        public String getUsername() { return username; }
        public void setUsername(String username) { this.username = username; }

        public String getPassword() { return password; }
        public void setPassword(String password) { this.password = password; }

        public int getPort() { return port; }
        public void setPort(int port) { this.port = port; }

        @Override
        public String toString() {
            return String.format("VPS{host='%s', username='%s', port=%d}", host, username, port);
        }
    }
    public boolean uninstallNetData() {
        try {
            log.warn("开始卸载NetData...");

            // 停止服务
            ProcessBuilder stopPb = new ProcessBuilder("sudo", "systemctl", "stop", "netdata");
            stopPb.start().waitFor();

            // 禁用服务
            ProcessBuilder disablePb = new ProcessBuilder("sudo", "systemctl", "disable", "netdata");
            disablePb.start().waitFor();

            // 卸载（根据安装方式选择）
            ProcessBuilder uninstallPb = new ProcessBuilder("sudo", "apt", "remove", "-y", "netdata");
            Process uninstallProcess = uninstallPb.start();
            boolean success = uninstallProcess.waitFor() == 0;

            if (success) {
                log.info("NetData卸载完成");
            } else {
                log.error("NetData卸载失败");
            }

            return success;

        } catch (Exception e) {
            log.error("卸载NetData失败", e);
            return false;
        }
    }
}
