import { defineConfig, presetUno, presetAttributify, presetIcons } from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetAttributify(),
    presetIcons({ scale: 1.15 }),
  ],
  safelist: [
    'i-mdi-view-dashboard-outline',
    'i-mdi-earth',
    'i-mdi-account-group-outline',
    'i-mdi-server',
    'i-mdi-email-outline',
    'i-mdi-database-outline',
    'i-mdi-play-circle-outline',
    'i-mdi-brain',
    'i-mdi-speedometer',
    'i-mdi-text-box-search-outline',
    'i-mdi-google',
    'i-mdi-microsoft',
    'i-mdi-aws',
    'i-mdi-key-outline',
    'i-mdi-cloud-outline',
    'i-mdi-nginx',
    'i-mdi-format-list-bulleted',
    'i-mdi-shield-check-outline',
    'i-mdi-file-document-outline',
    'i-mdi-tune',
    'i-mdi-swap-horizontal',
    'i-mdi-bell-outline',
    'i-mdi-notebook-outline',
    'i-mdi-migrate',
    'i-mdi-cellphone-key',
    'i-mdi-code-tags',
    'i-mdi-folder-outline',
    'i-mdi-harddisk',
    'i-mdi-lan',
    'i-mdi-lambda',
    'i-mdi-home-outline',
    'i-mdi-chevron-down',
    'i-mdi-leaf',
    'i-mdi-plus',
    'i-mdi-magnify',
    'i-mdi-bell-outline',
    'i-mdi-calendar-month-outline',
    'i-mdi-weather-night',
    'i-mdi-white-balance-sunny',
    'i-mdi-translate',
    'i-mdi-logout',
    'i-mdi-information-outline',
    'i-mdi-check-circle-outline',
    'i-mdi-close-circle-outline',
    'i-mdi-sync',
    'i-mdi-cpu-64-bit',
    'i-mdi-memory',
    'i-mdi-chart-donut',
    'i-mdi-chart-areaspline',
    'i-mdi-rocket-launch-outline',
    'i-mdi-account-plus-outline',
  ],
  theme: {
    colors: {
      brand: 'var(--brand)',
    },
  },
})
