server:
  port: 9856

telegram:
  bot:
    id: 6822503512
    token: 7994955517:AAFec4Jtpau_2-Roo4zt6_LbQge6U8bkTe4
    username: 哈哈哈
  #http 127.0.0.1:10809
  #sock 127.0.0.1:10808
  proxy:
    enabled: true
    type: HTTP
    host: 127.0.0.1
    port: 7890