server:
  port: 9856

telegram:
  bot:
    id: 682200000
    token: 799491231237:AASADFAASDFXXXXX
    username: 哈哈哈
  #http 127.0.0.1:10809
  #sock 127.0.0.1:10808
  proxy:
    enabled: true
    type: HTTP
    host: 127.0.0.1
    port: 7890